### ISSUE TITLE
Can't train due to Syntax error: "}" unexpected

### ISSUE THREAD

**Issue by JeongHanJun** [JCZ404/Semi-DETR#12]
Hello, thank you for the great research. 
I installed and ran it step by step as you mentioned, and the output is as follows. 
I'm curious how I can solve the issue and learn from it. Additionally, the shell script file was not modified.

I would greatly appreciate your reply. Have a good day!

![semi detr train print](https://github.com/JCZ404/Semi-DETR/assets/54197360/61bcfcef-ee1e-4c72-9a66-6fa269a7f0b9)

**Comment by qqssffgg** [comment]
我也遇见了这个问题，请问你解决了吗

**Comment by YijunQuan** [comment]
Use bash instead of sh
