### ISSUE TITLE
How to load DINODETR you implementation in detectors ???

### ISSUE THREAD

**Issue by Dong-Huh** [JCZ404/Semi-DETR#15]
you provide model(DINODETR) of configurations. but i got error forward_train  function in detr_ssod. 

detr_ssod/models/dino_detr_ssod.py 
error-->
sup_loss = self.student.forward_train(**data_groups["sup"], curr_step=self.curr_step)

may be i think that erros appear up, student model isn't builted, there's anything model codes in mmdet/models/detectors.

how to implement and how to solve this errors, if and if you provide model codes(DINO DETR), how to inject DINO DETR in mmdet/models/detectors

**Comment by JCZ404** [comment]
Hi, Thanks for your attention, and sorry for the late reply. Have you already solved the problem? If not you can provide more error information for me to assist you in solving this problem.

**Comment by tahirashehzadi** [comment]
sup_loss = self.student.forward_train(**data_groups["sup"], curr_step=self.curr_step)
TypeError: forward_train() got an unexpected keyword argument 'curr_step'

**Comment by dky6** [comment]
Hi ,
i got this error in detr_ssod/models/dino_detr_ssod.py
sup_loss = self.student.forward_train(**data_groups["sup"], curr_step=self.curr_step)
TypeError: forward_train() got an unexpected keyword argument 'curr_step'

When is remove curr_step=self.curr_step, then code is working fine.

**Comment by GloomyM** [comment]
> Hi , i got this error in detr_ssod/models/dino_detr_ssod.py sup_loss = self.student.forward_train(**data_groups["sup"], curr_step=self.curr_step) TypeError: forward_train() got an unexpected keyword argument 'curr_step' please solve this error

I think you can just remove the argument. I have removed it to test in my own dataset and it works.
