### ISSUE TITLE
deformable detr two_stage

### ISSUE THREAD

**Issue by nhw649** [JCZ404/Semi-DETR#16]
你好，请问基于deformable detr构建的semi detr有使用到two stage阶段（deformable detr论文中提出的）吗？

**Comment by nhw649** [comment]
开源代码中没找到deformable detr的配置。

**Comment by JCZ404** [comment]
谢谢关注，抱歉回复晚了。因为mmdet已经提供了Deformable DETR的实现以及相关的配置文件，为了保证整体代码的可读性，这里就没列出Deformable DETR的实现和配置。整体的半监督代码和DINO类似，您可以参考这里实现的基于DINO的半监督代码进行相应的修改～

**Comment by nhw649** [comment]
> 谢谢关注，抱歉回复晚了。因为mmdet已经提供了Deformable DETR的实现以及相关的配置文件，为了保证整体代码的可读性，这里就没列出Deformable DETR的实现和配置。整体的半监督代码和DINO类似，您可以参考这里实现的基于DINO的半监督代码进行相应的修改～

所以是使用了deformable-detr的two-stage吗？

**Comment by JCZ404** [comment]
你好，在deformable detr上，我们是基于mmdetection中提供的deformable detr配置进行实验的：https://github.com/open-mmlab/mmdetection/blob/main/mmdet/configs/deformable_detr/deformable_detr_r50_16xb2_50e_coco.py。
