### ISSUE TITLE
semi DETR code with deformable transformer

### ISSUE THREAD

**Issue by tahirashehzadi** [JCZ404/Semi-DETR#2]
Hi,
  Thank you so much for your amazing work. Could you please share semi DETR code wirh deformable transformer.

Thank you in advance!

**Comment by JCZ404** [comment]
Apologies for the delay in getting back to you. Lately, I've been quite occupied with various commitments and haven't had the time to continue organizing the code related to Deformable DETR. However, I'd like to highlight that the code for these modifications is relatively straightforward. You can take cues from our existing DINO codebase to implement it on your own.

**Comment by becauseofAI** [comment]
Is this existing DINO codebase a standard implementation for paper “DINO: DETR with Improved DeNoising Anchor Boxes for End-to-End Object Detection”? If not, what is the difference?

**Comment by JCZ404** [comment]
@becauseofAI You can find the official implementation for DINO at https://github.com/IDEA-Research/DINO. Our code borrows some codes from their official repo and reimplements DINO with mmdetection.
