### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by GloomyM** [JCZ404/Semi-DETR#22]
Hi, I want to know how to inference with the given weight and get the final result?

**Comment by GloomyM** [comment]
> you can refer to https://github.com/JCZ404/Semi-DETR#evaluation for the details of the inference.

What I mean is, how does the input image model infer and provide annotation results?

**Comment by Yuanyan266969** [comment]
> > you can refer to https://github.com/JCZ404/Semi-DETR#evaluation for the details of the inference.
> 
> Actually, I want to know how can I inference one image and get the result of detection not just getting the result of Ap

you can use the demo_image.py,and link to your checkpoint file,then you can inference on one image by give the picture to demo_image.py
