### ISSUE TITLE
Is there any other link to download a model weight file not via baidu?

### ISSUE THREAD

**Issue by lively2018** [JCZ404/Semi-DETR#23]
It is impossible to download  model weight files without the baidu registration. Could you share them via google drive?

**Comment by JCZ404** [comment]
Hi, Thanks for your interest in our work, we will release the new sharing link with Google Drive soon, including the model weights and our conda environment, please keep watching.

**Comment by lively2018** [comment]
Thank you for the responce. I'm looking forward to your update.

**Comment by JCZ404** [comment]
Hi, Thanks for your patience, we have already posted the new Google Driver link of our model weight and the environment. Please feel free to drop us an issue if you encounter any problems while using these files. Hope you enjoy it~

**Comment by lively2018** [comment]
Hello. I requested  access to the files. Could you please approve my request? Thanks.

**Comment by JCZ404** [comment]
Sorry for the permission error, it is already approved, please have a try.

**Comment by lively2018** [comment]
I successfully downloaded them. Thank you for sharing.

**Comment by lively2018** [comment]
I successfully downloaded them. Thank you for sharing.

**Comment by AlooTikkiii** [comment]
Could you also provide the weights for full-COCO and PASCAL Voc dataset

**Comment by JCZ404** [comment]
Ok, I will upload these files to Google Drive as soon as possible. Thanks for your patience.

**Comment by JCZ404** [comment]
@AlooTikkiii The checkpoint files of COCO-Full and PASCAL have already been uploaded to the Google Driver.
