### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'frombuffer'

### ISSUE THREAD

**Issue by Aishwarya1111** [JCZ404/Semi-DETR#25]
Getting this error even after upgrading torch to torch==1.10.1+cu113 and transformers==4.29.2 safetensors==0.3.0.

can you please help me with the exact version as the error is thrown due to version mismatch

**Comment by JCZ404** [comment]
Thanks for your interest, you can try our provided conda environment here: https://drive.google.com/file/d/1XoaMtMMVW4_qUGHXEOlEnjnOUaapyWwA/view
