### ISSUE TITLE
AttributeError: module ‘distutils‘ has no attribute ‘version‘

### ISSUE THREAD

**Issue by poorguy2001** [JCZ404/Semi-DETR#27]
使用from the Google Driver link: [semidetr_miniconda_cuda12.1_torch1.9.0+cu111_mmcv-full1.3.16.tar](https://drive.google.com/file/d/1XoaMtMMVW4_qUGHXEOlEnjnOUaapyWwA/view?usp=drive_link)配置的环境。在运行train_detr_ssod.py时出现module ‘distutils‘ has no attribute ‘version‘。
-----解决办法---------
1、升级PyTorch版本
2、更新/固定setuptools 包版本
3、修改init.py（推荐）
由于使用博主的环境包，怕升级pytorch版本带来其他问题，可直接修改site-packages/torch/utils/tensorboard/__init__.py 
法一：将from setuptools import distutils替换成from distutils.version import LooseVersion
同时注释LooseVersion = distutils.version.LooseVersion和del distutils这两行
法二：注释LooseVersion = distutils.version.LooseVersion
           if not hasattr(tensorboard, ‘version’) or LooseVersion(tensorboard.version) < LooseVersion(‘1.15’):
                raise ImportError(‘TensorBoard logging requires TensorBoard version 1.15 or above’)
            del LooseVersion

**Comment by AlooTikkiii** [comment]
Just go the file mentioned packages/torch/utils/tensorboard/init.py 

And comment out a few lines that has Loose Version. Or you can copy this code. 
import tensorboard
from setuptools import distutils

# LooseVersion = distutils.version.LooseVersion

# if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
#     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')

del distutils
# del LooseVersion
del tensorboard

from .writer import FileWriter, SummaryWriter  # noqa: F401
from tensorboard.summary.writer.record_writer import RecordWriter  # noqa: F401
